### PR TITLE
Fix issues #570, #575

### LINKED ISSUE #570: Very slow event processing (seconds)
The Windows event queue, as emulated under Wine, appears to work differently than the real one under Windows 10.

If you build my Rust test program, ui-mock, arc branch:

[code]
git clone https://github.com/John-Nagle/ui-mock.git
cd ui-mock
git checkout arc
cargo build --release --target x86_64-pc-windows-gnu --examples
cd target/x86_64-pc-windows-gnu/release/examples
wine ui-mock.exe
[/code]

it will run fine under real Windows 10. But, built on Ubuntu 22.04 LTS with current Rust, it behaves strangely.
Click on one of the big bars that says "placeholder", and you get get a login popup. It doesn't do anything; this is just a GUI dummy.
Type something into the user name box. 

On real Windows, characters are echoed at full speed.

[b]Under Wine 8 or 9, character echo is delayed about 3-4 seconds.[/b]

What seems to be happening is that the endless refreshing of the screen (this is a game-type program) is starving out event processing.

This uses the Rust crates Rend3, Winit, egui, and wgpu, all of which work cross-platform.
A newer version of Rend3 (see the Cargo.toml file for the rev number) has a different approach to the event loop. There are two callback functions - "event", and "redraw" in Rend3's framework. The framework itself does a request-redraw at the end of each redraw. This seems to starve out non-redraw event processing.

An earlier version of Rend3 did not have this problem. That older version can be  built as above, by removing the line 

    git checkout arc

This uses a different version of the Rend3 framework, one which only redraws when the event queue is empty.

"winit", a standard Rust crate, claims in its documentation that non-redraw events are always processed before redraws. But "winit", which has platform-dependent code for Windows, seems to assume, in the Windows platform code, that the underlying platform event queue does that. For real Windows, it does seem to do that. But Wine's event queue does not seem to work that way.

Also reported as a Wine bug: https://bugs.winehq.org/show_bug.cgi?id=56210

### LINKED ISSUE #575: "reqwest", "tokio", etc. pulled in by rend3-framework but not used
Only use seems to be converting an error type which never seems to be generated.

### PR DESCRIPTION
**Pull request by John-Nagle**
## Checklist

- CI Checked:
  - [X] `cargo fmt` has been ran
  - [X] `cargo clippy` reports no issues
  - [partial] `cargo test` succeeds (2 failures - scene-viewer tests need two.gltf files not present in the project, same as before.
  - [X] `cargo rend3-doc` has no warnings
  - [X] `cargo deny check` issues have been fixed or added to deny.toml
- Manually Checked:
  - [X] relevant examples/test cases run
  - [ ] changes added to changelog
    - [ ] Add credit to yourself for each change: `Added new functionality @githubname`.

## Related Issues

- Closes #570 
- Closes #575

## Description

Issue #570 required a mechanism to allow the application to override the default action of requesting a redraw immediately after redrawing each frame. So a new function, **handle_redraw_done**, was added to the **App** trait in rend3_framework. The default implementation of the trait mantains old behavior by requesting another redraw at the end of each redraw. Applications where the platform does not give non-redraw events priority over redraw events (this includes Windows executables running under Wine) can override the default behavior and redraw only when the event loop is about to wait.

Issue #575 was fixed by removing some dead code which imported "reqwest", pulling in but not using "tokio".

Also fixed the framework to allow the logger to be initialized more than once. This allows "cargo test" to run without panics.

### CODE REVIEW

**Comment by John-Nagle** [comment]
CI is failing because CI is using an old Rust compiler:

```
error: package `bumpalo v3.15.3` cannot be built because it requires rustc 1.73.0 or newer, while the currently active rustc version is 1.72.1
Either upgrade to rustc 1.73.0 or newer, or use
cargo update -p bumpalo@3.15.3 --precise ver
where `ver` is the latest version of `bumpalo` supporting rustc 1.72.1
```

Checking Bumpalo, here's the change that broke it: [Fix MSRV in Cargo.toml; bump to version 3.15.1 ](https://github.com/fitzgen/bumpalo/commit/f8597ceb3600807a902fa9692fb43c49e7b63b27)

Current stable Rust is rustc 1.76.0. [Github continuous integration for Rend3](https://github.com/BVE-Reborn/rend3/blob/trunk/.github/workflows/ci.yml) uses 1.72.

So the CI file needs an update.

**Comment by John-Nagle** [comment]
I can't fix the CI problem. I don't have permission to modify the CI workflow.

**Comment by cwfitzgerald** [comment]
@John-Nagle you can likely fix it, I just need to manually approve the CI run - this only happens on your first PR. On your second PR, CI will run automatically

**Comment by John-Nagle** [comment]
I got a Git permissions error trying to commit "@John-Nagle
[Increase Rust version in continuous integration from 1.72 to 1.76 so](https://github.com/BVE-Reborn/rend3/pull/576/commits/89c1d1bb7496b442a26dd6b9f994e39ddc4dea7e)". I don't fully understand the restrictions on that.

**Comment by John-Nagle** [comment]
CI for mac is stuck waiting for a runner, for 23 hours now. All other runs finished in the first minute. Is that normal?

**Comment by John-Nagle** [comment]
How can I get this un-stuck? The mac CI waited 24 hours for a runner and then Github aborted the job.

**Comment by cwfitzgerald** [comment]
I can't push to your branch as it's trunk - but will merge this and fix it.

**Pull request merged**
