### PR TITLE
Update `wgpu` dependency to 0.19.0.

### PR DESCRIPTION
**Pull request by kpreid**
## Checklist

- CI Checked:
  - [x] `cargo fmt` has been ran
  - [x] `cargo clippy` reports no issues
  - [ ] `cargo test` succeeds
  - [ ] `cargo rend3-doc` has no warnings
  - [ ] `cargo deny check` issues have been fixed or added to deny.toml
- Manually Checked:
  - [X] relevant examples/test cases run
  - [X] changes added to changelog
    - [X] Add credit to yourself for each change: `Added new functionality @githubname`.

## Description

Updates `wgpu` to the new release 0.19.0.

* Updates `wgpu-profiler` to match.
* `rend3_gltf::util::format_components()` is now implemented by calling `wgpu::TextureFormat::components()`, which seems to be the same function.

### CODE REVIEW

**Comment by kpreid** [comment]
Incorporated updating `wgpu-profiler`.

**Comment by kpreid** [comment]
It occurs to me that there's a subtlety here — with `wgpu` 0.19 no longer having the `webgl` feature imply _disabling_ WebGPU, this means that as long as `rend3` depends on `wgpu` with default features, it'll be impossible to compile `rend3` applications for web without using `web_sys_unstable_apis`. So, I think this change will also have to disable default features on the `wgpu` dependency, or it'll put users in a bad situation. (Unfortunately, this means that users will have to think about `wgpu` backend feature selection explicitly…)

**Comment by kpreid** [comment]
This should be ready to merge, in principle. Tests don't pass locally, though:

```
---- animation::test stdout ----
thread 'animation::test' panicked at /Users/kpreid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/env_logger-0.10.2/src/logger.rs:479:14:
Builder::init should not be called after logger initialized: SetLoggerError(())
stack backtrace:
...
   4: env_logger::logger::Builder::init
             at /Users/kpreid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/env_logger-0.10.2/src/logger.rs:478:9
   5: rend3_framework::App::register_logger
             at /Users/kpreid/Projects/rust/contributing/rend3/rend3-framework/src/lib.rs:74:9
   6: rend3_examples_package::tests::test_app::{{closure}}
             at ./src/tests.rs:17:5
```

I'm not sure what's up with that, but it seems to be a preexisting issue.

**Comment by cwfitzgerald** [comment]
>  I'm not sure what's up with that, but it seems to be a preexisting issue.

You need `cargo nextest` - I should implement the same "scream at you" error as wgpu has.

**Comment by kpreid** [comment]
> You need `cargo nextest`

Then the testing steps in `build.bash` (and the PR template) are stale and should be updated or deleted, because they contain `cargo test`.

**Comment by kpreid** [comment]
Updated `naga` too to satisfy cargo-deny.

**Comment by kpreid** [comment]
@cwfitzgerald The mac CI failure has no details — failure to start perhaps?

In any case, what does this PR need to move forward?

**Comment by cwfitzgerald** [comment]
Yeah I pulled my local runner for security concerns - let's merge this and I'll fix it in a follow up.

**Pull request merged**
